services:
  - type: web
    name: minecraft-keepalive-bot
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MC_HOST
        value: enchanted.kingsnetwork.uk
      - key: MC_PORT
        value: 25813
      - key: MC_USERNAME
        value: KeepAliveBot
      - key: MC_AUTH
        value: offline
